<?php
/**
 * CompareCustomEnvironment
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diffy
 *
 * API for visual regression testing tool Diffy
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CompareCustomEnvironment Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompareCustomEnvironment implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CompareCustomEnvironment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'env1' => 'string',
'env2' => 'string',
'env1_url' => 'string',
'env2_url' => 'string',
'env1_creds_mode' => 'bool',
'env1_creds_user' => 'string',
'env1_creds_pass' => 'string',
'env2_creds_mode' => 'bool',
'env2_creds_user' => 'string',
'env2_creds_pass' => 'string',
'commit_sha' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'env1' => null,
'env2' => null,
'env1_url' => 'url',
'env2_url' => 'url',
'env1_creds_mode' => null,
'env1_creds_user' => null,
'env1_creds_pass' => null,
'env2_creds_mode' => null,
'env2_creds_user' => null,
'env2_creds_pass' => null,
'commit_sha' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'env1' => 'env1',
'env2' => 'env2',
'env1_url' => 'env1Url',
'env2_url' => 'env2Url',
'env1_creds_mode' => 'env1CredsMode',
'env1_creds_user' => 'env1CredsUser',
'env1_creds_pass' => 'env1CredsPass',
'env2_creds_mode' => 'env2CredsMode',
'env2_creds_user' => 'env2CredsUser',
'env2_creds_pass' => 'env2CredsPass',
'commit_sha' => 'commitSha'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'env1' => 'setEnv1',
'env2' => 'setEnv2',
'env1_url' => 'setEnv1Url',
'env2_url' => 'setEnv2Url',
'env1_creds_mode' => 'setEnv1CredsMode',
'env1_creds_user' => 'setEnv1CredsUser',
'env1_creds_pass' => 'setEnv1CredsPass',
'env2_creds_mode' => 'setEnv2CredsMode',
'env2_creds_user' => 'setEnv2CredsUser',
'env2_creds_pass' => 'setEnv2CredsPass',
'commit_sha' => 'setCommitSha'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'env1' => 'getEnv1',
'env2' => 'getEnv2',
'env1_url' => 'getEnv1Url',
'env2_url' => 'getEnv2Url',
'env1_creds_mode' => 'getEnv1CredsMode',
'env1_creds_user' => 'getEnv1CredsUser',
'env1_creds_pass' => 'getEnv1CredsPass',
'env2_creds_mode' => 'getEnv2CredsMode',
'env2_creds_user' => 'getEnv2CredsUser',
'env2_creds_pass' => 'getEnv2CredsPass',
'commit_sha' => 'getCommitSha'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ENV1_CUSTOM = 'custom';
const ENV2_CUSTOM = 'custom';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEnv1AllowableValues()
    {
        return [
            self::ENV1_CUSTOM,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEnv2AllowableValues()
    {
        return [
            self::ENV2_CUSTOM,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['env1'] = isset($data['env1']) ? $data['env1'] : null;
        $this->container['env2'] = isset($data['env2']) ? $data['env2'] : null;
        $this->container['env1_url'] = isset($data['env1_url']) ? $data['env1_url'] : null;
        $this->container['env2_url'] = isset($data['env2_url']) ? $data['env2_url'] : null;
        $this->container['env1_creds_mode'] = isset($data['env1_creds_mode']) ? $data['env1_creds_mode'] : null;
        $this->container['env1_creds_user'] = isset($data['env1_creds_user']) ? $data['env1_creds_user'] : null;
        $this->container['env1_creds_pass'] = isset($data['env1_creds_pass']) ? $data['env1_creds_pass'] : null;
        $this->container['env2_creds_mode'] = isset($data['env2_creds_mode']) ? $data['env2_creds_mode'] : null;
        $this->container['env2_creds_user'] = isset($data['env2_creds_user']) ? $data['env2_creds_user'] : null;
        $this->container['env2_creds_pass'] = isset($data['env2_creds_pass']) ? $data['env2_creds_pass'] : null;
        $this->container['commit_sha'] = isset($data['commit_sha']) ? $data['commit_sha'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getEnv1AllowableValues();
        if (!is_null($this->container['env1']) && !in_array($this->container['env1'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'env1', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getEnv2AllowableValues();
        if (!is_null($this->container['env2']) && !in_array($this->container['env2'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'env2', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets env1
     *
     * @return string
     */
    public function getEnv1()
    {
        return $this->container['env1'];
    }

    /**
     * Sets env1
     *
     * @param string $env1 env1
     *
     * @return $this
     */
    public function setEnv1($env1)
    {
        $allowedValues = $this->getEnv1AllowableValues();
        if (!is_null($env1) && !in_array($env1, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'env1', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['env1'] = $env1;

        return $this;
    }

    /**
     * Gets env2
     *
     * @return string
     */
    public function getEnv2()
    {
        return $this->container['env2'];
    }

    /**
     * Sets env2
     *
     * @param string $env2 env2
     *
     * @return $this
     */
    public function setEnv2($env2)
    {
        $allowedValues = $this->getEnv2AllowableValues();
        if (!is_null($env2) && !in_array($env2, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'env2', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['env2'] = $env2;

        return $this;
    }

    /**
     * Gets env1_url
     *
     * @return string
     */
    public function getEnv1Url()
    {
        return $this->container['env1_url'];
    }

    /**
     * Sets env1_url
     *
     * @param string $env1_url URL for first page
     *
     * @return $this
     */
    public function setEnv1Url($env1_url)
    {
        $this->container['env1_url'] = $env1_url;

        return $this;
    }

    /**
     * Gets env2_url
     *
     * @return string
     */
    public function getEnv2Url()
    {
        return $this->container['env2_url'];
    }

    /**
     * Sets env2_url
     *
     * @param string $env2_url URL for second page
     *
     * @return $this
     */
    public function setEnv2Url($env2_url)
    {
        $this->container['env2_url'] = $env2_url;

        return $this;
    }

    /**
     * Gets env1_creds_mode
     *
     * @return bool
     */
    public function getEnv1CredsMode()
    {
        return $this->container['env1_creds_mode'];
    }

    /**
     * Sets env1_creds_mode
     *
     * @param bool $env1_creds_mode Enable basic auth
     *
     * @return $this
     */
    public function setEnv1CredsMode($env1_creds_mode)
    {
        $this->container['env1_creds_mode'] = $env1_creds_mode;

        return $this;
    }

    /**
     * Gets env1_creds_user
     *
     * @return string
     */
    public function getEnv1CredsUser()
    {
        return $this->container['env1_creds_user'];
    }

    /**
     * Sets env1_creds_user
     *
     * @param string $env1_creds_user Username
     *
     * @return $this
     */
    public function setEnv1CredsUser($env1_creds_user)
    {
        $this->container['env1_creds_user'] = $env1_creds_user;

        return $this;
    }

    /**
     * Gets env1_creds_pass
     *
     * @return string
     */
    public function getEnv1CredsPass()
    {
        return $this->container['env1_creds_pass'];
    }

    /**
     * Sets env1_creds_pass
     *
     * @param string $env1_creds_pass Password
     *
     * @return $this
     */
    public function setEnv1CredsPass($env1_creds_pass)
    {
        $this->container['env1_creds_pass'] = $env1_creds_pass;

        return $this;
    }

    /**
     * Gets env2_creds_mode
     *
     * @return bool
     */
    public function getEnv2CredsMode()
    {
        return $this->container['env2_creds_mode'];
    }

    /**
     * Sets env2_creds_mode
     *
     * @param bool $env2_creds_mode Enable basic auth
     *
     * @return $this
     */
    public function setEnv2CredsMode($env2_creds_mode)
    {
        $this->container['env2_creds_mode'] = $env2_creds_mode;

        return $this;
    }

    /**
     * Gets env2_creds_user
     *
     * @return string
     */
    public function getEnv2CredsUser()
    {
        return $this->container['env2_creds_user'];
    }

    /**
     * Sets env2_creds_user
     *
     * @param string $env2_creds_user Username
     *
     * @return $this
     */
    public function setEnv2CredsUser($env2_creds_user)
    {
        $this->container['env2_creds_user'] = $env2_creds_user;

        return $this;
    }

    /**
     * Gets env2_creds_pass
     *
     * @return string
     */
    public function getEnv2CredsPass()
    {
        return $this->container['env2_creds_pass'];
    }

    /**
     * Sets env2_creds_pass
     *
     * @param string $env2_creds_pass Password
     *
     * @return $this
     */
    public function setEnv2CredsPass($env2_creds_pass)
    {
        $this->container['env2_creds_pass'] = $env2_creds_pass;

        return $this;
    }

    /**
     * Gets commit_sha
     *
     * @return string
     */
    public function getCommitSha()
    {
        return $this->container['commit_sha'];
    }

    /**
     * Sets commit_sha
     *
     * @param string $commit_sha Gitbug commit SHA for sending github Check
     *
     * @return $this
     */
    public function setCommitSha($commit_sha)
    {
        $this->container['commit_sha'] = $commit_sha;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
